name: Russell Morgan
favicon: null
layout_spectrum: 0.1858327491208911
typography_spectrum: 0.37271361239254475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.03373170970007777
  lightness: 0.10883032507263124
  saturation: 0.13636380899697542
  rhythmicContrast: 0.4662318902555853
purpose: []
